### ISSUE TITLE
Update README.md info on slurry sep memo

### ISSUE THREAD

**Issue by sashahafner** [AU-BCE-EE/AU-MHB#2]
@JohannaPedersen it has been finalized, right? Could you update the links and description if needed. Related question: are the AU Pure links really the official source for all these ministry documents?

**Comment by JohannaPedersen** [comment]
@sashahafner yes, and published. I checked the description and didn't find anything to add. The link has been added. 
I tried to find another source, but didn't succeed, so my guess is that the pure/DCA link is it is only (and official) one.

**Comment by sashahafner** [comment]
Thanks @JohannaPedersen
